# Generated by Django 5.2.1 on 2025-05-25 19:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_eventosasistencia_delete_registroasistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventosasistencia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventosasistencia',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
